name: health_prod
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - lightgbm
  - scikit-learn
  - scipy=1.11
  - conda-forge::imbalanced-learn
  - conda-forge::scikit-plot
  - ipykernel
  - conda-forge::seaborn
  - inflection
  - flask
  - google-auth
  - gspread
  - conda-forge::python-dotenv
